import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import { format } from "prettier";

const output = new URL(
	"../src/lib/game/world-map/world-map-settlements.ts",
	import.meta.url,
);
// ACE landblock geometry, matching src/lib/game/landblocks.ts; these are file-format facts.
const landblockSize = 192;
const worldExtent = 255 * landblockSize;

/** Convert the retained SQL recipe's raw TSV into deterministic, branded frontend data. */
export async function generateWorldMapSettlements(
	input: string,
): Promise<string> {
	const lines = input.trimEnd().split(/\r?\n/);
	if (lines.length === 1 && lines[0] === "")
		throw new Error("Settlement query output is empty.");
	const names = new Set<string>();
	const sources = new Set<string>();
	const rows = lines.map((line, index) => {
		const columns = line.split("\t");
		if (columns.length !== 8)
			throw new Error(`Row ${index + 1}: expected eight TSV columns.`);
		const [name, sourceWcid, cell, localX, localY, localZ, count, sourceKind] =
			columns;
		if (
			!name ||
			name.trim() !== name ||
			[...name].some(
				(character) =>
					character.charCodeAt(0) < 32 || character.charCodeAt(0) === 127,
			)
		)
			throw new Error(`Row ${index + 1}: invalid settlement name.`);
		if (names.has(name)) throw new Error(`Duplicate settlement name: ${name}.`);
		names.add(name);
		if (sourceKind !== "portal" && sourceKind !== "vendor")
			throw new Error(`${name}: unknown anchor source ${sourceKind}.`);
		if (!/^[1-9]\d*$/.test(sourceWcid) || Number(sourceWcid) > 0xffffffff)
			throw new Error(`${name}: invalid source WCID.`);
		const sourceKey = `${sourceKind}:${sourceWcid}`;
		if (sources.has(sourceKey))
			throw new Error(`${name}: duplicate anchor source ${sourceKey}.`);
		sources.add(sourceKey);
		if (!/^[1-9]\d*$/.test(count) || Number(count) !== lines.length)
			throw new Error(
				`${name}: incomplete or ambiguous selection; expected ${count} rows, received ${lines.length}.`,
			);
		if (cell === "NULL")
			throw new Error(
				`${name}: ${sourceKind} ${sourceWcid} has no anchor record.`,
			);
		if (!/^[0-9a-fA-F]{8}$/.test(cell))
			throw new Error(`${name}: invalid anchor cell ID.`);
		const cellId = Number.parseInt(cell, 16);
		if (cellId >>> 24 >= 255 || ((cellId >>> 16) & 255) >= 255)
			throw new Error(`${name}: anchor names an unauthored landblock axis.`);
		const terrainCell = cellId & 0xffff;
		if ((terrainCell === 0 && sourceKind === "portal") || terrainCell > 64)
			throw new Error(`${name}: anchor is not an outdoor placement.`);
		const numbers = [localX, localY, localZ].map((value) => {
			if (
				!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(value) ||
				!Number.isFinite(Number(value))
			)
				throw new Error(`${name}: invalid anchor coordinate ${value}.`);
			return Number(value);
		});
		const x = ((cellId >>> 24) & 255) * landblockSize + numbers[0];
		const z = -(((cellId >>> 16) & 255) * landblockSize + numbers[1]);
		if (x < 0 || x > worldExtent || z > 0 || z < -worldExtent)
			throw new Error(`${name}: anchor lies outside the outdoor world.`);
		return {
			name,
			source:
				sourceKind === "portal"
					? `ACE portal ${sourceWcid}, destination`
					: `ACE vendor ${sourceWcid}, placement`,
			cell: cell.toUpperCase(),
			position: [x, numbers[2], z],
		};
	});
	rows.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
	const entries = rows.map(
		({ name, source, cell, position }) =>
			`// ${source} cell 0x${cell}.\n{ name: ${JSON.stringify(name)}, position: sceneVector3([${position.join(", ")}]) },`,
	);
	return format(
		`// Generated by npm run generate:world-map-settlements. Do not edit coordinates manually.
// Source selection: apps/holtburger-tools/sql/world-map-settlements.sql.
import { sceneVector3 } from "../../assets/ac-frame";
import type { WorldMapSettlement } from "./settlements";

/** Verified default-world portal arrivals and vendor placements used as settlement anchors. */
export const WORLD_MAP_SETTLEMENTS: readonly WorldMapSettlement[] = [
${entries.join("\n")}
];
`,
		{ parser: "typescript", useTabs: true },
	);
}

if (
	process.argv[1] &&
	pathToFileURL(process.argv[1]).href === import.meta.url
) {
	if (process.argv.length !== 3)
		throw new Error(
			"Usage: npm run generate:world-map-settlements -- <query-output.tsv>",
		);
	// Validate and format all rows before replacing the checked-in output.
	const generated = await generateWorldMapSettlements(
		await readFile(process.argv[2], "utf8"),
	);
	await writeFile(output, generated);
	console.log(`Generated ${fileURLToPath(output)}.`);
}
