pub fn property_name(id: u32) -> &'static str {
    match id {
        0 => "Undef",
        1 => "ItemType",
        2 => "CreatureType",
        3 => "PaletteTemplate",
        5 => "EncumbranceVal",
        6 => "ItemsCapacity",
        7 => "ContainersCapacity",
        8 => "Mass",
        9 => "ValidLocations",
        12 => "StackSize",
        19 => "Value",
        20 => "CoinValue",
        21 => "TotalExperience",
        22 => "AvailableCharacter",
        24 => "AvailableSkillCredits",
        25 => "Level",
        31 => "ChannelsAllowed",
        32 => "ChannelsActive",
        40 => "CombatMode",
        97 => "LoginTimestamp",
        98 => "CreationTimestamp",
        112 => "AdvocateLevel",
        129 => "VitaeCpPool",
        131 => "MaterialType",
        134 => "PlayerKillerStatus",
        159 => "Unknown159",
        381..=389 => "UnknownExtra",
        _ => "Property",
    }
}
