[package]
name = "holtburger-debug-harness"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
holtburger-content.workspace = true
holtburger-core.workspace = true
holtburger-dat.workspace = true
tokio.workspace = true
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
hex.workspace = true
byteorder.workspace = true
