// Generated by npm run generate:world-map-settlements. Do not edit coordinates manually.
// Source selection: apps/holtburger-tools/sql/world-map-settlements.sql.
import { sceneVector3 } from "../../assets/ac-frame";
import type { WorldMapSettlement } from "./settlements";

/** Verified default-world portal arrivals and vendor placements used as settlement anchors. */
export const WORLD_MAP_SETTLEMENTS: readonly WorldMapSettlement[] = [
	// ACE portal 42827, destination cell 0x0FB90009.
	{ name: "Ahurenga", position: sceneVector3([2923, 0.005, -35528.6]) },
	// ACE portal 42823, destination cell 0x8F58003B.
	{ name: "Al-Arqas", position: sceneVector3([27639.851, 9.326, -16956.183]) },
	// ACE portal 42830, destination cell 0x8588002C.
	{ name: "Al-Jalima", position: sceneVector3([25656.359, 90.049, -26207.47]) },
	// ACE portal 42819, destination cell 0xC6A90009.
	{ name: "Arwic", position: sceneVector3([38062.805, 42.005, -32452.219]) },
	// ACE portal 7194, destination cell 0x1133001F.
	{ name: "Ayan Baqur", position: sceneVector3([3352.1, 64.8, -9958.2]) },
	// ACE portal 42845, destination cell 0xCE410007.
	{ name: "Baishi", position: sceneVector3([39564.6, 55.1, -12632.8]) },
	// ACE portal 1102, destination cell 0xBDD00006.
	{ name: "Bandit Castle", position: sceneVector3([36304.9, 115.1, -40056.5]) },
	// ACE portal 42825, destination cell 0x21B00017.
	{ name: "Bluespire", position: sceneVector3([6384.19, 0.005, -33957.89]) },
	// ACE portal 24579, destination cell 0x2B120029.
	{
		name: "Candeth Keep",
		position: sceneVector3([8376.642, 10.112, -3457.549]),
	},
	// ACE portal 42818, destination cell 0xBB9F0040.
	{
		name: "Cragstone",
		position: sceneVector3([36073.358, 54.005, -30696.251]),
	},
	// ACE vendor 2498, placement cell 0x90D00000.
	{
		name: "Crater Lake Village",
		position: sceneVector3([27707.0085, 297.207, -40043.151]),
	},
	// ACE portal 43003, destination cell 0x5A9C0004.
	{ name: "Danby's Outpost", position: sceneVector3([17303.5, 6, -30029.1]) },
	// ACE portal 42813, destination cell 0xDA75002B.
	{ name: "Dryreach", position: sceneVector3([41988, 18.005, -22524]) },
	// ACE portal 42815, destination cell 0xCE940035.
	{ name: "Eastham", position: sceneVector3([39703.053, 17.417, -28528.61]) },
	// ACE portal 42839, destination cell 0x49F00013.
	{ name: "Eastwatch", position: sceneVector3([14086, 170.005, -46150]) },
	// ACE portal 42999, destination cell 0x38F7001B.
	{ name: "Fiun Outpost", position: sceneVector3([10843, -0.095, -47478]) },
	// ACE portal 43001, destination cell 0x2681001D.
	{ name: "Fort Tethana", position: sceneVector3([7373.7, 240, -24876.1]) },
	// ACE portal 42814, destination cell 0xA0A40025.
	{
		name: "Glenden Wood",
		position: sceneVector3([30816.302, 59.955, -31607.847]),
	},
	// ACE portal 42826, destination cell 0x2BB5003C.
	{ name: "Greenspire", position: sceneVector3([8434.958, 0.005, -34838.57]) },
	// ACE portal 42846, destination cell 0xE64E002F.
	{ name: "Hebian-to", position: sceneVector3([44298.304, 20.04, -15137.905]) },
	// ACE portal 42820, destination cell 0xA9B40019.
	{ name: "Holtburg", position: sceneVector3([32532, 94, -34567.1]) },
	// ACE portal 42848, destination cell 0xBA170039.
	{ name: "Kara", position: sceneVector3([35893.2, 167.7, -4419.2]) },
	// ACE portal 42822, destination cell 0x9F440012.
	{ name: "Khayyaban", position: sceneVector3([30618, 31.885, -13080.553]) },
	// ACE portal 42850, destination cell 0xE822002A.
	{ name: "Kryst", position: sceneVector3([44676.7, 20.1, -6565.9]) },
	// ACE portal 42844, destination cell 0xDC3C0011.
	{ name: "Lin", position: sceneVector3([42299.72, 18.958, -11530.774]) },
	// ACE portal 42838, destination cell 0xA21E001A.
	{ name: "Linvak Tukal", position: sceneVector3([31187, 560.4, -5798]) },
	// ACE portal 42816, destination cell 0xC0800007.
	{
		name: "Lytelthorpe",
		position: sceneVector3([36875.723, 33.028, -24731.56]),
	},
	// ACE portal 43004, destination cell 0xF224001A.
	{ name: "MacNiall's Freehold", position: sceneVector3([46545.8, 0, -6945]) },
	// ACE portal 42842, destination cell 0xE6320021.
	{ name: "Mayoi", position: sceneVector3([44267.417, 29.908, -9610.763]) },
	// ACE portal 42843, destination cell 0xE63E0022.
	{ name: "Nanto", position: sceneVector3([44256.96, 74.542, -11941.722]) },
	// ACE portal 42828, destination cell 0x95D60033.
	{ name: "Neydisa", position: sceneVector3([28754.9, 99.8, -41159.3]) },
	// ACE portal 43002, destination cell 0xF6820033.
	{
		name: "Oolutanga's Refuge",
		position: sceneVector3([47377.7, 58.005, -25009.855]),
	},
	// ACE portal 42812, destination cell 0x49B70021.
	{
		name: "Plateau Village",
		position: sceneVector3([14116.1, 238.6, -35156.8]),
	},
	// ACE portal 42833, destination cell 0x9722003A.
	{ name: "Qalaba'r", position: sceneVector3([29160.354, 102.005, -6552.618]) },
	// ACE portal 42836, destination cell 0x17B2002A.
	{ name: "Redspire", position: sceneVector3([4548.623, 44.005, -34201.809]) },
	// ACE portal 42817, destination cell 0xC98C0028.
	{ name: "Rithwic", position: sceneVector3([38705.666, 22.005, -27070.259]) },
	// ACE portal 42834, destination cell 0x977B000C.
	{ name: "Samsur", position: sceneVector3([29017.811, 0.005, -23689.853]) },
	// ACE portal 42835, destination cell 0x33D90015.
	{ name: "Sanamar", position: sceneVector3([9851.1, 52.005, -41764.3]) },
	// ACE portal 42849, destination cell 0xC95B0001.
	{ name: "Sawato", position: sceneVector3([38606.8, 12, -17472.3]) },
	// ACE portal 42840, destination cell 0xDA55001D.
	{ name: "Shoushi", position: sceneVector3([41940.8, 20, -16419]) },
	// ACE portal 42998, destination cell 0x26EC003D.
	{ name: "Silyun", position: sceneVector3([7471.927, 80.005, -45422.334]) },
	// ACE portal 42811, destination cell 0x64D5000B.
	{ name: "Stonehold", position: sceneVector3([19230, 78, -40946]) },
	// ACE portal 43000, destination cell 0x1DB60016.
	{ name: "Timaru", position: sceneVector3([5639.3873, 90.005, -35078.291]) },
	// ACE portal 42841, destination cell 0xF5590034.
	{ name: "Tou-Tou", position: sceneVector3([47192.59, 20.005, -17168.8]) },
	// ACE portal 42829, destination cell 0x876C0008.
	{ name: "Tufa", position: sceneVector3([25922, 18, -20922.9]) },
	// ACE portal 42821, destination cell 0xA260003C.
	{ name: "Uziz", position: sceneVector3([31286.919, 20.005, -18519.934]) },
	// ACE portal 4218, destination cell 0x3F310007.
	{ name: "Wai Jhou", position: sceneVector3([12119, -0.1, -9557.6]) },
	// ACE portal 42837, destination cell 0x23DA002C.
	{ name: "Westwatch", position: sceneVector3([6860.9, 2.005, -41942]) },
	// ACE portal 42832, destination cell 0x934B0021.
	{ name: "Xarabydun", position: sceneVector3([28332.3, 18.1, -14406.1]) },
	// ACE portal 42847, destination cell 0xB46F001E.
	{ name: "Yanshi", position: sceneVector3([34635.2, 34.69, -21436.1]) },
	// ACE portal 42824, destination cell 0x7D64000D.
	{ name: "Yaraq", position: sceneVector3([24031.9, 11.9, -19304.6]) },
	// ACE portal 42831, destination cell 0x80900013.
	{ name: "Zaikhal", position: sceneVector3([24640.863, 124.005, -27703.687]) },
];
