[package]
name = "holtburger-3d"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"
default-run = "holtburger-3d"

[features]
profile-devtools = ["tauri/devtools"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow.workspace = true
holtburger-content.workspace = true
holtburger-common.workspace = true
holtburger-core.workspace = true
holtburger-dat.workspace = true
holtburger-world.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
tokio.workspace = true
geo = "0.33.1"
hex.workspace = true
log.workspace = true

[dev-dependencies]
tempfile.workspace = true
